# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170729_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shortened_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
