# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170729_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.StructureUnit'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='default_deputy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deputy_by_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Employee'),
        ),
    ]
