# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170729_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureunit',
            name='shortened_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.StructureUnit'),
        ),
    ]
