# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closure_act_date',
            field=models.DateField(blank=True, null=True, verbose_name='closure act date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='closure_act_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='completion date'),
        ),
    ]
