# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170729_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='created_by_id',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='plan',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
